### ISSUE TITLE
ERROR in ./node_modules/scrollStore/index.ts

### ISSUE THREAD

**Issue by jberall** [xe4me/scrollstore#5]
Angular 5.2

Module build failed: Error: C:\angular-modules-test\thorall_template\node_modules\scrollStore\index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\angular-modules-test\thorall_template\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:663:23)
    at plugin.done.then (C:\angular-modules-test\thorall_template\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./src/app/app.module.ts 22:20-42
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

**Comment by vmachacek** [comment]
+1

**Comment by Svrkota-S** [comment]
Anyone manage to fix this error?
